name: Haskell CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  build:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2.7.11
      id: setup-haskell # Add id to reference outputs in later steps
      with:
        ghc-version: '9.2'
        cabal-version: '3.6'

    - name: Cache Cabal store and dist-newstyle
      uses: actions/cache@v4 # Updated to v4
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-ghc-${{ steps.setup-haskell.outputs.ghc-version }}-cabal-${{ steps.setup-haskell.outputs.cabal-version }}-deps-${{ hashFiles('**/cabal.project.freeze', '**/*.cabal', '**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-ghc-${{ steps.setup-haskell.outputs.ghc-version }}-cabal-${{ steps.setup-haskell.outputs.cabal-version }}-deps-
          ${{ runner.os }}-ghc-${{ steps.setup-haskell.outputs.ghc-version }}-cabal-${{ steps.setup-haskell.outputs.cabal-version }}-
          ${{ runner.os }}-ghc-

    - name: Build project (including dependencies) and run tests
      run: |
        cabal update
        cabal build --enable-tests --enable-benchmarks all
        cabal test --enable-tests --enable-benchmarks all
